name: dart_jikan
description: A starting point for Dart libraries or applications.
version: 0.1.0
homepage: https://github.com/xamantra/dart_jikan

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  http: ^0.12.2
  meta: ^1.2.4

dev_dependencies:
  flutter_test: # kinda weird here but it works!
    sdk: flutter
  
  pedantic: 1.9.0
  remove_from_coverage: 1.0.7