name: dart_jikan
description: Dart wrapper for Jikan MAL api. Well documented and highly tested.
version: 0.4.0
homepage: https://github.com/xamantra/dart_jikan

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.0
  meta: ^1.3.0

dev_dependencies:  
  test: ^1.16.7