name: dart_jikan
description: Dart wrapper for Jikan MAL api. Well documented and highly tested.
version: 0.1.4
homepage: https://github.com/xamantra/dart_jikan

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  http: ^0.12.2
  meta: ^1.2.4
  jikan_models:
    git:
      url: git@github.com:xamantra/dart_jikan.git
      path: jikan_models/

dev_dependencies:  
  test: 1.14.3