name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    # container:
    #   image: google/dart:2.8.4
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v1.4.0
    - name: Install Packages
      run: dart pub get
    - name: Tests
      run: flutter test --coverage
    - name: Ignore auto-generate models in coverage
      run: dart pub run remove_from_coverage:remove_from_coverage -f coverage/lcov.info -r '\bmodels\b'
    - name: Code Coverage -> Check
      uses: ChicagoFlutter/lcov-cop@v1.0.0
