name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: google/dart:2.8.4
    steps:
    - uses: actions/checkout@v2
    - name: Install Packages
      run: pub get
    - name: Install coverage
      run: dart pub global activate coverage
    - name: Run tests
      run: dart test --coverage="coverage"
    - name: Format coverage
      run: format_coverage --lcov --in=coverage --out=coverage/lcov.info --packages=.packages --report-on=lib
    - name: Ignore auto-generate models in coverage
      run: pub run remove_from_coverage:remove_from_coverage -f coverage/lcov.info -r '\bmodels\b'
